### ISSUE TITLE
showProductDialog does nothing

### ISSUE THREAD

**Issue by caspahouzer** [dezinezync/TiStoreView#3]
```
Operating System
  Name                        = Mac OS X
  Version                     = 10.12.1
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 17179869184

Node.js
  Node.js Version             = 4.4.4
  npm Version                 = 2.15.1

Titanium CLI
  CLI Version                 = 5.0.6

Titanium SDK
  SDK Version                 = 5.5.1.GA
  SDK Path                    = /Users/sebastianklaus/Library/Application Support/Titanium/mobilesdk/osx/5.5.1.GA
  Target Platform             = iphone
```

When I execute the code from the example, nothing happens. Not on simulator and also not on device

**Comment by dezinezync** [comment]
@caspahouzer StoreView isn't available on the sim. Not sure why it doesn't work on the device. Roping in @hansemannn. 

PS: I'm no longer working on Ti Modules. I'm keeping it open to the community.

**Comment by hansemannn** [comment]
@caspahouzer It's device only. And on the device, it takes some time to load, so you usually show a loading indicator and listen to the events to toggle it. Also check if you are running on main-thread or not. It may need adjustments on non-main-thread apps?

**Comment by hansemannn** [comment]
@dezinezync Can you add me to the collaborator list then? Or we move it to my fork if that's something you can work with.

**Comment by dezinezync** [comment]
@hansemannn I've added you as a collaborator. Let me know how it works. If not, we'll move it over. Thank you for helping us out.

**Comment by dezinezync** [comment]
@hansemannn handling the main-thread bit should be the module's responsibility? Generally, UIKit stuff should always be run on the main thread. 
So essentially, always call the following line on the main thread using GCD: 
https://github.com/dezinezync/TiStoreView/blob/master/Classes/ComDezinezyncStoreviewModule.m#L95

**Comment by hansemannn** [comment]
Yes, that should already be ensured with `ENSURE_UI_THREAD` but since it's inside the block, we can simply wrap it with `TiThreadPerformOnMainThread` and it will work for the kroll-thread, e.g.

``` objc
TiThreadPerformOnMainThread(^{
    [[TiApp app] showModalController:storeProductViewController animated:YES];
}, NO);
```

I can push an update tomorrow.

**Comment by caspahouzer** [comment]
No luck so far. Even with a loading indicator. The events are not triggered

**Comment by hansemannn** [comment]
@caspahouzer Didn't do the commit so far. Try the following build and I will push afterwards:

[com.dezinezync.storeview-iphone-1.1.1.zip](https://github.com/dezinezync/TiStoreView/files/571578/com.dezinezync.storeview-iphone-1.1.1.zip)
